---
title: "els_covid_inflammation"
author: "Justin"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}
library(corrr)
library(corrplot)
library(psych)
library(tidyverse)
#test code
```

```{r, load data}
# source("COVID.Import.Data.R")
ELS.T3 = read.csv(file = "Data/ELS_T3_COVID_Curated.csv")
COVID = read.csv(file = "Data/ELS_COVID_CHILD_04.22.2020.csv")
```

```{r, wrangling}
# set up T3 inflammation data
df.blood = ELS.T3 %>% 
  drop_na(IL.1b) %>% 
  dplyr::select(ELS_ID, Timepoint.T3, Sex, age_s2.T3,
         #contains("tscore"),
        # -contains("RADS"),
         114:128) %>% 
  mutate(IL.1b_mfi = log(IL.1b), 
         IL.6_mfi = log(IL.6),
         IL.10_mfi = log(IL.10),
         TNF.a_mfi = log(TNF.a),
         CRP_mfi = log(CRP))
# head(df.blood)

# set up Covid timepoint
df.covid = COVID %>%
  drop_na(MASC_total.TC) %>%
  dplyr::select(ELS_ID, Child_Age.TC,
         contains("MASC"),
         starts_with("PSS"),
         contains("STAI"),
         contains("CESD")
         )
# head(df.covid)

# merge df's together
df.merge = left_join(df.blood, df.covid, "ELS_ID") %>% 
  drop_na(MASC_total.TC) %>%
  dplyr::select(-Timepoint.T3)


head(df.merge)

#TH: create a composite measure of inflammation (when I tried mutate this doesn't 'stick' in the df...maybe I'm doing something wrong?)

df.merge$infcomp_mfi = scale(df.merge$IL.1b_mfi,scale=T)+scale(df.merge$IL.6_mfi,scale=T)+scale(df.merge$IL.10_mfi,scale=T)+scale(df.merge$TNF.a_mfi,scale=T)
```

```{r correlations}
df.corr = df.merge %>% 
  dplyr::select(-Child_Age.TC) %>% 
  dplyr::select(contains("mfi"),
         contains("BMI"),
         contains("TC")) %>% 
  correlate() %>% 
  mutate_if(is.numeric, round, 3) 

# correlation plot
p.corr_plot = df.corr %>% 
  rplot(colors = c("red","blue")) + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p.corr_plot

# network plot
p.network_plot = df.corr %>% 
  network_plot(min_cor = 0.2,
               colors = c("red","white", "blue"),
               repel = TRUE)
p.network_plot
```

```{r tiffany's code for a corrplot}
#TH: I edited this a lot
vars=c("infcomp_mfi","IL.1b_mfi","IL.6_mfi","IL.10_mfi","TNF.a_mfi", "CRP_mfi","child_bmi.T3","MASC_total.TC","MASC_harm.TC","MASC_social.TC","MASC_phys.TC","PSS_total.TC","STAI_total.TC","CESDC_total.TC")

datacorr<-df.merge[vars]
M<-cor(datacorr,method="pearson",use="pairwise.complete.obs")
#generating the p-values:
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(M)
  
#head(p.mat[, 1:5]) #this will display first 5 variables


#plot the correlation matrix and cross-out those under p<0.05
par(cex=0.3) #aesthetics - adjust size of correlation est
corrplot(M,method="number", 
          tl.cex=1.5,tl.srt=55,type="upper", p.mat = p.mat, sig.level = 0.05)  
```

```{r}
# significance table
df.sig = df.corr %>% 
  select(-rowname) %>% 
  cor.mtest

df.sig %>% 
  range(df.sig, MASC_phys.TC)
```


```{r save files}
df.corr %>% 
  write_csv(path = "Results/covid_inflammation_corrs.csv", col_names = TRUE)
ggsave("./Results/corr_plot.png", p.corr_plot)
ggsave("./Results/network_plot.png", p.network_plot)
```

